/**
 * ╔══════════════════════════════════════════════════════╗
 * ║          CONFERENCE COMPANION — 會議設定檔           ║
 * ║  每次換會議只需要更新這一個檔案，其餘全部保持不動    ║
 * ╚══════════════════════════════════════════════════════╝
 *
 * 當前會議：ESHG 2026
 * 地點：哥特堡，瑞典
 * 日期：2026年6月13–16日
 */

window.CONFERENCE_CONFIG = {

  // ── 基本資訊 ──────────────────────────────────────────
  name:       "ESHG 2026",
  subtitle:   "歐洲人類遺傳學大會・哥特堡 Gothenburg, Sweden",
  shortLabel: "ESHG 2026 哥特堡",
  dates:      "2026年6月13–16日",
  location:   "Svenska Mässan，哥特堡，瑞典",
  startDate:  "2026-06-13T08:00:00+02:00",

  // ── Google Drive 儲存設定 ─────────────────────────────
  driveFolderName: "ESHG2026",
  notesFileName:   "eshg2026_notes.json",

  // ── 報到時間 ──────────────────────────────────────────
  registrationTimes: [
    "6/12（五）14:00–18:00",
    "6/13（六）07:30–20:15",
    "6/14（日）08:00–19:00",
    "6/15（一）08:00 起",
  ],

  // ── 重要連結 ──────────────────────────────────────────
  links: [
    ["完整議程",      "https://2026.eshg.org/programme-at-a-glance-local/"],
    ["Session表",    "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme"],
    ["企業衛星場次", "https://2026.eshg.org/satellite-meetings/corporate-sessions/"],
    ["講者名單",     "https://2026.eshg.org/programme-at-a-glance-local/speakers/"],
    ["官方 App",     "https://itunes.apple.com/app/european-soc-of-human-genetic/id1390551688"],
  ],

  // ── Google 地圖 ───────────────────────────────────────
  mapsUrl: "https://maps.google.com/?q=Svenska+Massan+Gothenburg",
  venue:   "Svenska Mässan，Mässans gata 24, 412 51 Gothenburg",

  // ── AI 自動更新設定 ───────────────────────────────────
  updateUrls: [
    "https://2026.eshg.org/programme-at-a-glance-local/",
    "https://2026.eshg.org/programme-at-a-glance-local/speakers/",
  ],
  keySessionsDesc: "S13細胞遺傳學2.0（週一08:30）、I17結構染色體變異（週一17:00）、I18生殖攜帶者篩查（週一17:00）、S23產前檢測的未來（週二09:00）、I01 Episignatures（週六08:30）",
  specialistProfile: "OB/GYN產前診斷醫師",

  // ── 出發前自動更新時間點 ──────────────────────────────
  checkpoints: [
    { key: "w1", label: "出發前一週", days: 7, icon: "📅" },
    { key: "d3", label: "出發前三天", days: 3, icon: "📋" },
    { key: "d1", label: "出發前一天", days: 1, icon: "🔔" },
  ],

  // ── 個人備忘提醒 ──────────────────────────────────────
  personalReminders: [
    "週一 S13 細胞遺傳學2.0 — 細胞遺傳主持人考試備考重點",
    "週一 I17 結構性染色體變異 — 與考試內容直接相關",
    "週二 S23 產前檢測的未來 — 全程必到，不可讓步",
    "週一 I18 攜帶者篩查 — 對安安婦幼中心業務有參考價值",
    "建議主動聯繫：Arianna Tucci、Erik Sistermans",
  ],

  // ── 天數標籤 ──────────────────────────────────────────
  days: {
    sat: "週六 6/13",
    sun: "週日 6/14",
    mon: "週一 6/15",
    tue: "週二 6/16",
  },

  sessions: {

    // ── 週六 6/13 ─────────────────────────────────────────
    sat: [
      { time: "08:30–10:00", items: [
        { id: "s_i01", b: "int", l: "互動", title: "I01 Episignatures：超越二元分類的臨床與產前應用",
          tags: ["star","prenatal"],
          speakers: ["Hans Björnsson (Iceland)","Arianna Tucci (UK)"],
          detail: "DNA甲基化表觀遺傳特徵在超越二元分類框架中的臨床潛力，包含長讀長定序（LRS）最新進展以及產前診斷應用前景。產前診斷必看！",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "s_e01", b: "edu", l: "教育", title: "E01 臨床基因組策展（變異分類）",
          tags: ["star"],
          speakers: ["Ahmad Abou Tayoun (UAE)","Ellen McDonagh (UK)"],
          detail: "ACMG/AMP變異分類框架更新、ClinGen策展標準與實際案例討論。建立細胞遺傳學實驗室品管流程的直接參考。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "s_s01", b: "sym", l: "研討", title: "S01 從GWAS尋找效應基因",
          tags: ["star"],
          speakers: ["Len Pennacchio (USA)","Hilary Finucane (USA)"],
          detail: "從GWAS位點利用功能基因組學、eQTL分析、CRISPR篩選識別因果效應基因的最新策略。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "s_s02", b: "sym", l: "研討", title: "S02 X染色體新發現：跨物種比較視角",
          tags: ["cyto"],
          speakers: ["Joost Gribnau (NL)","Tuuli Lappalainen (SE)"],
          detail: "X染色體失活、劑量補償機制的跨物種比較研究。細胞遺傳學相關。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "10:00–10:30", brk: "☕ 咖啡休息・海報張貼・展覽" },
      { time: "10:30–12:00", parallel: true, items: [
        { id: "s_c01", b: "con", l: "C01", title: "C01 產前診斷與不孕",
          tags: ["prenatal","star"], speakers: ["（詳見大會APP）"],
          detail: "胎兒染色體與基因組診斷技術最新發展；著床前基因診斷（PGT-A/M/SR）更新；cfDNA應用於不孕症評估；反覆流產遺傳基礎探討。\n\n⭐ 與您的專科高度相關",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "s_c02", b: "con", l: "C02", title: "C02 智能障礙與自閉症",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "新型智能障礙/自閉症相關基因發現；外顯子組/基因組定序在發展遲緩病例的診斷率；表型–基因型關聯分析；家族遺傳諮詢策略。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "s_c03", b: "con", l: "C03", title: "C03 生物資訊與機器學習",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "AI輔助變異分類工具比較；深度學習判讀基因組變異；臨床分析管道自動化與標準化；臨床生物資訊最佳實踐。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "s_c04", b: "con", l: "C04", title: "C04 遺傳性癌症風險",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "BRCA1/2以外的遺傳性乳癌卵巢癌基因研究；Lynch症候群篩查更新；多基因風險評分在癌症預防；人口篩查政策國際比較。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "s_c05", b: "con", l: "C05", title: "C05 心臟與血管遺傳",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "肥厚型心肌病遺傳基礎新研究；心律不整遺傳性通道病變；家族性高膽固醇血症管理；基因組篩查預防突發心臟猝死。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "s_c06", b: "con", l: "C06", title: "C06 感覺器官（聽力／視力）",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "遺傳性耳聾基因圖譜更新；視網膜色素變性與遺傳性眼疾新進展；基因療法在遺傳性眼病；聽覺植入基因選擇考量。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "s_c07", b: "con", l: "C07", title: "C07 基因組醫學與公衛政策",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "全國性基因組計畫成果；新生兒基因組篩查擴展辯論；基因數據分享倫理框架；基因組醫學的健康不平等議題。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
      ]},
      { time: "13:40–16:00", items: [
        { id: "s_pl12", b: "pl", l: "全體", title: "PL1–2 開幕全體大會・Leena Peltonen 獎講",
          tags: ["star"], speakers: ["ESHG主席","Leena Peltonen獎得主"],
          detail: "13:40 開幕致詞 / 14:00 Leena Peltonen獎講 / 14:15 開幕全體大會演講。大會最重要開場儀式，不宜錯過。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "17:00–18:30", items: [
        { id: "s_pl3", b: "pl", l: "全體", title: "PL3「有什麼新鮮事？」重點摘要場次",
          tags: ["star"], speakers: ["精選自投稿摘要"],
          detail: "從大會投稿中精選最具突破性研究成果進行口頭發表。掌握本年度最新動態的最佳管道。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "20:15–21:45", items: [
        { id: "s_mix", b: "soc", l: "社交", title: "🥂 開幕交流派對",
          tags: [], speakers: [],
          detail: "大會官方交流派對，認識國際同行的最佳機會。建議攜帶名片主動交流。",
          link: "https://2026.eshg.org/myconference/official-events/" },
      ]},
    ],

    // ── 週日 6/14 ─────────────────────────────────────────
    sun: [
      { time: "08:30–10:00", items: [
        { id: "u_e02", b: "edu", l: "教育", title: "E02 AI用於功能基因組學與遺傳關聯分析",
          tags: ["star"], speakers: ["Oliver Stegle (DE)","Julien Gagneur (DE)"],
          detail: "深度學習預測調控元件、AI輔助剪接變異預測、多模態基因組數據整合。了解AI如何改變基因組醫學實踐。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "u_i04", b: "int", l: "互動", title: "I04 長讀長定序入門",
          tags: ["star","cyto"], speakers: ["Adam Phillippy (USA)","Lars Feuk (SE)"],
          detail: "PacBio HiFi / Oxford Nanopore原理與臨床轉化。聚焦結構性變異偵測、重複序列解析、相位分析（phasing）。細胞遺傳學實驗室未來技術布局參考！",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "u_s05", b: "sym", l: "研討", title: "S05 重複序列擴增：被低估的疾病根源",
          tags: ["cyto"], speakers: ["Rosa Rademakers (BE)","Sarah Weckhuysen (BE)"],
          detail: "串聯重複序列擴增在神經疾病中的作用，以及長讀長定序在偵測傳統短讀長定序無法識別變異中的革命性角色。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "u_s07", b: "sym", l: "研討", title: "S07 多基因評分：臨床實施是否已準備好？",
          tags: ["star"], speakers: ["Danielle Posthuma (NL)","Nina Mars (FI)"],
          detail: "多基因風險評分跨族群適用性、臨床效用評估、醫療系統整合挑戰的重要政策討論。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "10:00–10:30", brk: "☕ 咖啡休息・海報自由參觀" },
      { time: "10:30–12:00", parallel: true, items: [
        { id: "u_c15", b: "con", l: "C15", title: "C15 cfDNA與液態切片",
          tags: ["prenatal","star"], speakers: ["（詳見大會APP）"],
          detail: "新一代 cfDNA 技術應用；NIPT 偵測範圍擴展；液態切片在早期妊娠評估；多組學 cfDNA 整合分析。\n\n⭐ 產前診斷核心主題",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c16", b: "con", l: "C16", title: "C16 罕見病診斷突破",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "長期未確診罕見病的全基因組解決方案；RNA定序輔助診斷困難病例；深度內含子變異偵測；診斷後醫療管理改變。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c17", b: "con", l: "C17", title: "C17 族群遺傳學",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "非歐洲族群基因組多樣性；遺傳祖先分析方法論；跨族群多基因評分校正；地中海/中東/亞洲族群遺傳疾病盛行率。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c18", b: "con", l: "C18", title: "C18 表觀遺傳與甲基化",
          tags: ["cyto"], speakers: ["（詳見大會APP）"],
          detail: "DNA甲基化圖譜在疾病診斷；表觀遺傳時鐘應用；組蛋白修飾在發育疾病；表觀遺傳療法新進展。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c19", b: "con", l: "C19", title: "C19 神經遺傳與肌肉疾病",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "肌萎縮性側索硬化症新基因研究；脊髓肌萎縮治療長期追蹤；遺傳性肌病基因治療；周邊神經疾病基因圖譜。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c20", b: "con", l: "C20", title: "C20 藥物遺傳學",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "PGx臨床實施成果；藥物基因組學在精神科用藥；癌症精準用藥新生物標記；PGx在兒科的特殊考量。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c21", b: "con", l: "C21", title: "C21 遺傳諮詢新議題",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "次要發現通知實務；基因組結果回饋給未成年人的倫理；遠距遺傳諮詢模式評估；AI輔助遺傳諮詢工具。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
      ]},
      { time: "17:00–18:30", parallel: true, items: [
        { id: "u_c22", b: "con", l: "C22", title: "C22 染色體結構異常",
          tags: ["cyto","star"], speakers: ["（詳見大會APP）"],
          detail: "複雜染色體重排解析；染色體碎裂新病例；長讀長定序偵測隱匿性易位；平衡易位攜帶者的生育風險精算。\n\n🔬 細胞遺傳核心主題",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c23", b: "con", l: "C23", title: "C23 代謝與溶酶體疾病",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "溶酶體儲積症基因治療最新試驗；新生兒篩查擴展；苯丙酮尿症飲食管理基因輔助；代謝疾病生物標記開發。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c24", b: "con", l: "C24", title: "C24 基因治療臨床進展",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "AAV基因治療長期追蹤安全性數據；血友病基因治療實際成效；鐮刀型貧血/地中海貧血基因治療全球更新；體內基因編輯首批臨床結果。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c25", b: "con", l: "C25", title: "C25 複雜多基因疾病",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "多基因風險評分在常見病的臨床效用；糖尿病/高血壓遺傳架構更新；多表型GWAS新方法；環境與基因交互作用模型。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c26", b: "con", l: "C26", title: "C26 粒線體遺傳疾病",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "粒線體DNA突變負荷動態；粒線體替代療法倫理辯論更新；核基因編碼粒線體疾病的WES診斷率；粒線體基因編輯可行性。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c27", b: "con", l: "C27", title: "C27 免疫與自體免疫遺傳",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "原發性免疫缺乏基因診斷擴展；自體炎症疾病新致病基因；HLA複雜區域精細分型；免疫療法的遺傳預測標記。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "u_c28", b: "con", l: "C28", title: "C28 功能基因組學方法",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "CRISPR功能篩選在變異致病性評估；單細胞多組學整合；空間轉錄組學在人類發育；基因組調控元件解析。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
      ]},
    ],

    // ── 週一 6/15 ─────────────────────────────────────────
    mon: [
      { time: "08:30–10:00", items: [
        { id: "m_e04", b: "edu", l: "教育", title: "E04 AI基因組學的ELSI（倫理、法律、社會議題）",
          tags: ["star"], speakers: ["Kelly Ormond (CH)","Eva Winkler (DE)"],
          detail: "算法公平性、基因隱私、知情同意、責任歸屬。建立符合倫理的AI輔助診斷流程的直接指引。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "m_i12", b: "int", l: "互動", title: "I12 基因組報告的撰寫、閱讀與解讀藝術",
          tags: ["star"], speakers: ["Heidi Rehm (USA)","Erik Sistermans (NL)"],
          detail: "如何撰寫清晰可行動的基因組報告？涵蓋ACGS/ACMG報告標準、結構化報告模板。臨床實踐有直接幫助。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "m_s13", b: "sym", l: "研討", title: "★ S13 細胞遺傳學 2.0 – 長讀長基因組",
          tags: ["star","cyto"], speakers: ["Adam Phillippy (USA)","Jose Espejo Valle-Inclan (PT)","Lars Feuk (SE)"],
          detail: "【細胞遺傳核心場次・備考重點！】\n・染色體組裝精度提升（telomere-to-telomere）\n・複雜結構變異完整解析\n・從核型到基因組的實驗室轉型策略討論",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "10:00–10:30", brk: "☕ 咖啡休息・海報自由參觀" },
      { time: "10:30–12:00", parallel: true, items: [
        { id: "m_c29", b: "con", l: "C29", title: "C29 產前基因組診斷進展",
          tags: ["prenatal","star"], speakers: ["（詳見大會APP）"],
          detail: "胎兒基因組分析的臨床路徑優化；超音波異常胎兒的快速WES/WGS；胎盤嵌合體處理流程；VUS在產前的管理。\n\n⭐ 本場最重要並行選擇之一",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "m_c30", b: "con", l: "C30", title: "C30 結構性基因組變異",
          tags: ["cyto","star"], speakers: ["（詳見大會APP）"],
          detail: "長讀長定序在SV偵測精度比較；複雜重排完整解析；微陣列 vs WGS在臨床SV診斷；拷貝數變異致病性新分類標準。\n\n🔬 細胞遺傳核心主題",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "m_c31", b: "con", l: "C31", title: "C31 RNA研究與剪接變異",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "RNA定序在診斷困難病例的附加診斷率；深度內含子剪接變異偵測工具比較；轉錄本長讀長定序在臨床；異常剪接的mRNA監控機制。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "m_c32", b: "con", l: "C32", title: "C32 癌症體細胞突變",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "腫瘤全基因組定序在精準治療選擇；液態切片ctDNA監測治療反應；TMB與MSI作為免疫治療生物標記；體細胞vs胚系區分挑戰。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "m_c33", b: "con", l: "C33", title: "C33 遲發型神經退化疾病",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "帕金森氏症遺傳多樣性；阿茲海默症風險基因與APOE4交互作用；額顳葉失智症新致病基因；神經退化疾病生物標記血液檢測。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "m_c34", b: "con", l: "C34", title: "C34 基因組醫學整合與政策",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "基因組醫學納入國家醫療體系的障礙與解方；臨床醫師基因組識讀教育；再分析策略與頻率；全球基因組數據共享政策框架。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "m_c35", b: "con", l: "C35", title: "C35 機器學習與精準醫學",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "大型語言模型在臨床基因組學；表型驅動基因優先化工具新評估；多模態AI整合基因組與影像；聯邦學習在基因組數據共享。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
      ]},
      { time: "14:00–15:30", items: [
        { id: "m_e05", b: "edu", l: "教育", title: "E05 長讀長RNA定序與表觀轉錄組學",
          tags: ["star","cyto"], speakers: ["Cole Trapnell (USA)","Ana Conesa (ES)"],
          detail: "完整剪接本識別、RNA修飾（m6A等表觀轉錄組標記）、轉錄本融合偵測。診斷困難病例的RNA研究直接參考。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "m_i13", b: "int", l: "互動", title: "I13 幾乎被我們遺漏的突變",
          tags: ["star"], speakers: ["Claudia Carvalho (USA)","David Adams (UK)"],
          detail: "深度內含子變異、複雜結構重排、假基因干擾、低豐度體細胞嵌合突變。實際病例導向，高度臨床相關。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "17:00–18:30", items: [
        { id: "m_i17", b: "int", l: "互動", title: "★ I17 結構性染色體變異",
          tags: ["star","cyto"], speakers: ["Jose Espejo Valle-Inclan (PT)","Claudia Carvalho (USA)"],
          detail: "【細胞遺傳核心場次・備考重點！】\n・染色體微陣列 vs 長讀長定序比較\n・染色體碎裂（chromothripsis）識別\n・平衡易位精確斷點定位",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "m_i18", b: "int", l: "互動", title: "★ I18 生殖攜帶者篩查：衝擊與後續",
          tags: ["star","prenatal"], speakers: ["Danny M. Cohn (NL)","Stina Lou (DK)","Roseline Favresse (FR)"],
          detail: "【產前診斷核心場次！】\n・擴展性攜帶者篩查（ECS）不同策略比較\n・篩查結果的遺傳諮詢與心理影響\n・台灣/亞洲族群攜帶頻率數據意義",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "20:00起", items: [
        { id: "m_eve", b: "soc", l: "社交", title: "🎉 ESHG 交流之夜",
          tags: [], speakers: [],
          detail: "大會最重要社交活動，人脈建立的黃金時段。地點另行公告。",
          link: "https://2026.eshg.org/myconference/official-events/" },
      ]},
    ],

    // ── 週二 6/16 ─────────────────────────────────────────
    tue: [
      { time: "09:00–10:30", items: [
        { id: "t_s22", b: "sym", l: "研討", title: "S22 多組學解決複雜病例",
          tags: ["star"], speakers: ["David Adams (UK)","Sebastian Lunke (AU)"],
          detail: "整合WGS、RNA定序、蛋白質組學解決長期未確診罕見疾病。提升診斷率的策略洞見。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "t_s23", b: "sym", l: "研討", title: "★ S23 產前檢測的未來",
          tags: ["star","prenatal"], speakers: ["Wendy Chung (USA)","Arianna Tucci (UK)","Stina Lou (DK)"],
          detail: "【本次大會最重要產前診斷場次！全程必到！】\n・NIPT技術極限與新一代應用\n・胎兒全基因組定序的臨床整合\n・cfDNA非預期發現處理\n・基因編輯在產前介入的倫理前沿",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "t_s25", b: "sym", l: "研討", title: "S25 基因編輯進入臨床",
          tags: ["star"], speakers: ["Gerald Schwank (CH)","Julia Vitarello (USA)"],
          detail: "CRISPR/Cas9基因編輯療法最新臨床試驗數據，以及下一代體內基因編輯療法的安全性與效力。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "t_e07", b: "edu", l: "教育", title: "E07 染色體外DNA（ecDNA）：染色體外的生命",
          tags: ["cyto"], speakers: ["Anton G Henssen (DE)","Jasmine Plummer (USA)"],
          detail: "ecDNA在癌症驅動基因擴增中的角色，以及在癌症進化與治療抵抗中的機制。細胞遺傳學與癌症遺傳學交叉前沿。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
      { time: "10:30–11:00", brk: "☕ 咖啡休息" },
      { time: "11:00–12:30", parallel: true, items: [
        { id: "t_c36", b: "con", l: "C36", title: "C36 胎兒醫學與子宮內治療",
          tags: ["prenatal","star"], speakers: ["（詳見大會APP）"],
          detail: "子宮內基因治療可行性研究；胎兒水腫/結構異常的基因組診斷流程；臨終照護遺傳諮詢；產前確診後的家庭決策支持。\n\n⭐ 產前診斷最終場次，收官重點",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "t_c37", b: "con", l: "C37", title: "C37 基因編輯臨床成果",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "鐮刀型貧血/β-地貧 CRISPR治療兩年追蹤；鹼基編輯首批人體試驗；先天代謝異常體內基因編輯；脫靶效應長期安全監測。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "t_c38", b: "con", l: "C38", title: "C38 罕見病登記與患者夥伴",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "歐盟ERN成果評估；患者組織參與研究的新模式；罕見病自然病史研究；跨國數據共享加速診斷。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "t_c39", b: "con", l: "C39", title: "C39 無創診斷技術前沿",
          tags: ["prenatal"], speakers: ["（詳見大會APP）"],
          detail: "單分子定序在cfDNA低豐度偵測；甲基化組分析識別組織來源；RNA in cfDNA的疾病訊號；母血循環胎兒細胞。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "t_c40", b: "con", l: "C40", title: "C40 基因組醫學實施挑戰",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "中低收入國家基因組醫學可及性；遺傳檢測費用給付政策；臨床醫師訓練需求評估；患者基因識讀促進策略。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
        { id: "t_c41", b: "con", l: "C41", title: "C41 多元族群健康公平",
          tags: [], speakers: ["（詳見大會APP）"],
          detail: "亞洲/非洲/拉丁美洲基因組代表性不足問題；H3Africa等大型多元族群計畫；PRS跨族群校正進展；遺傳診斷在不同族群的表現差異。",
          link: "https://cattendee.abstractsonline.com/meeting/21531/pages/Scientific_Programme" },
      ]},
      { time: "12:30–13:30", brk: "🍱 午餐休息" },
      { time: "13:30–16:00", items: [
        { id: "t_pl456", b: "pl", l: "全體", title: "PL4–6 三大獎項講座（ELPAG・ESHG・Mendel獎）",
          tags: ["star"], speakers: ["ELPAG獎得主","ESHG Award得主","Mendel獎得主"],
          detail: "13:30 ELPAG獎・13:50 ESHG最高榮譽獎・14:35 Mendel終身成就獎。每位得主通常帶來畢生最重要的研究成果。",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
        { id: "t_pl7", b: "pl", l: "全體", title: "PL7 頒獎典禮・閉幕致詞",
          tags: [], speakers: ["ESHG主席"],
          detail: "EJHG Citation Awards / ESHG Early Career Awards / Dian Donnai & Jill Clayton-Smith Award / 閉幕致詞",
          link: "https://2026.eshg.org/programme-at-a-glance-local/" },
      ]},
    ],

  }, // end sessions

}; // end CONFERENCE_CONFIG
